//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        public int FaceId { get; set; }
        public string Face1 { get; set; }
    }
}
