//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRent
    {
        public long PropertyId { get; set; }
        public string Locality { get; set; }
        public int PropertyType { get; set; }
        public Nullable<decimal> Area { get; set; }
        public int AU { get; set; }
        public Nullable<int> ADType { get; set; }
        public Nullable<int> AvailableStatus { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public decimal ExpectedPrice { get; set; }
        public Nullable<decimal> SecurityAmount { get; set; }
        public Nullable<decimal> MaintenanceCharges { get; set; }
        public Nullable<int> BathroomNum { get; set; }
        public Nullable<int> TotalFloor { get; set; }
        public Nullable<int> FloorNum { get; set; }
        public bool FurnishedType { get; set; }
        public string Address { get; set; }
        public string ProjectSociety { get; set; }
        public bool CarParking { get; set; }
        public Nullable<int> FacingId { get; set; }
        public int CityId { get; set; }
        public string Description { get; set; }
        public string Mobile { get; set; }
        public string PropertyName { get; set; }
        public bool BikeParking { get; set; }
        public bool Lift { get; set; }
        public bool Water { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    }
}
